import { useState, useRef, useEffect } from 'react'
import { PRIORITIES } from '../../constants'
import { fmtDate } from '../../utils/format'
import { Ico } from '../icons/Ico'

function addDays(n) {
  const d = new Date(); d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

// ── Snooze dropdown ───────────────────────────────────────────────
function SnoozeMenu({ onSnooze, onClose }) {
  const ref = useRef(null)
  useEffect(() => {
    const fn = e => { if (ref.current && !ref.current.contains(e.target)) onClose() }
    document.addEventListener('mousedown', fn)
    return () => document.removeEventListener('mousedown', fn)
  }, [onClose])

  const opts = [
    { label: 'מחר',    value: addDays(1) },
    { label: '3 ימים', value: addDays(3) },
    { label: 'שבוע',   value: addDays(7) },
  ]

  return (
    <div ref={ref} style={{
      position: 'absolute', left: 0, top: '100%', zIndex: 200,
      background: 'var(--card)', border: '1px solid var(--border)',
      borderRadius: 8, boxShadow: '0 4px 16px rgba(0,0,0,.12)',
      padding: 6, minWidth: 130,
    }}>
      {opts.map(o => (
        <button key={o.value} onClick={() => { onSnooze(o.value); onClose() }}
          style={{ display:'block', width:'100%', textAlign:'right', padding:'7px 12px',
            border:'none', background:'none', cursor:'pointer', color:'var(--fg)', fontSize:13,
            borderRadius:6 }}
          onMouseEnter={e => e.target.style.background='var(--bg2)'}
          onMouseLeave={e => e.target.style.background='none'}
        >⏰ {o.label}</button>
      ))}
    </div>
  )
}

// ── Task row ──────────────────────────────────────────────────────
function TaskRow({ t, contacts, onToggle, onEdit, onDelete, onSnooze }) {
  const [snoozeOpen, setSnoozeOpen] = useState(false)
  const di = fmtDate(t.dueDate)
  const pr = PRIORITIES.find(p => p.value === t.priority) || PRIORITIES[1]
  const cname = contacts.find(c => c.id === t.contactId)?.name || ''

  return (
    <div className="task-row" style={{ position: 'relative' }}>
      <div className={`tck ${t.completed ? 'dn' : ''}`} onClick={() => onToggle(t.id)}>
        {t.completed && <Ico.check/>}
      </div>
      <div className="tb">
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span className={`tt-txt ${t.completed ? 'dn' : ''}`}>{t.title}</span>
          {t.autoGenerated && (
            <span style={{ fontSize: 10, background: '#ede9fe', color: '#7c3aed', borderRadius: 4, padding: '1px 5px' }}>auto</span>
          )}
        </div>
        <div className="tm">
          <span className={`badge ${pr.badge}`}>{pr.label}</span>
          {cname && <span className="badge b-gray">{cname}</span>}
          {di && <span style={{ fontSize: 12, color: di.ov ? 'var(--danger)' : 'var(--muted)' }}>{di.text}{di.ov ? ' (באיחור)' : ''}</span>}
          {t.snoozedUntil && !t.completed && (
            <span style={{ fontSize: 11, color: '#8b5cf6', background: '#ede9fe', borderRadius: 4, padding: '1px 6px' }}>
              😴 נדחה עד {t.snoozedUntil}
            </span>
          )}
        </div>
      </div>
      <div className="ta" style={{ gap: 4 }}>
        {/* Snooze */}
        {!t.completed && (
          <div style={{ position: 'relative' }}>
            <button className="icon-btn" title="דחה משימה" onClick={() => setSnoozeOpen(v => !v)}
              style={{ fontSize: 14 }}>⏰</button>
            {snoozeOpen && (
              <SnoozeMenu onSnooze={v => onSnooze(t.id, v)} onClose={() => setSnoozeOpen(false)}/>
            )}
          </div>
        )}
        <button className="icon-btn" onClick={() => onEdit(t)}><Ico.edit/></button>
        <button className="icon-btn" style={{ color: 'var(--danger)' }}
          onClick={() => { if (window.confirm('למחוק?')) onDelete(t.id) }}><Ico.trash/></button>
      </div>
    </div>
  )
}

// ── Page ──────────────────────────────────────────────────────────
export default function TasksPage({ tasks, contacts, onAdd, onUpdate, onDelete, onToggle, onSnooze }) {
  const [filter, setFilter] = useState('today')
  const [modal, setModal]   = useState(null)

  const todayStr = new Date().toISOString().split('T')[0]
  const today    = new Date(); today.setHours(0,0,0,0)

  const isVisible = t => !t.snoozedUntil || t.snoozedUntil <= todayStr

  const cnts = {
    today:   tasks.filter(t => !t.completed && t.dueDate === todayStr && isVisible(t)).length,
    overdue: tasks.filter(t => !t.completed && t.dueDate && t.dueDate < todayStr && isVisible(t)).length,
    open:    tasks.filter(t => !t.completed && isVisible(t)).length,
    snoozed: tasks.filter(t => !t.completed && t.snoozedUntil && t.snoozedUntil > todayStr).length,
    done:    tasks.filter(t => t.completed).length,
  }

  const filtered = tasks.filter(t => {
    if (filter === 'today')   return !t.completed && t.dueDate === todayStr && isVisible(t)
    if (filter === 'overdue') return !t.completed && t.dueDate && t.dueDate < todayStr && isVisible(t)
    if (filter === 'open')    return !t.completed && isVisible(t)
    if (filter === 'snoozed') return !t.completed && t.snoozedUntil && t.snoozedUntil > todayStr
    if (filter === 'done')    return t.completed
    return true
  }).sort((a, b) => {
    if (a.dueDate && b.dueDate) return a.dueDate.localeCompare(b.dueDate)
    if (a.dueDate) return -1
    if (b.dueDate) return 1
    return 0
  })

  function TaskModal({ task }) {
    const [form, setForm] = useState(() => task || { title: '', contactId: '', priority: 'medium', dueDate: '' })
    const f   = k => e => setForm(p => ({ ...p, [k]: e.target.value }))
    const sub = e => {
      e.preventDefault()
      if (!form.title.trim()) return
      task ? onUpdate(task.id, form) : onAdd(form)
      setModal(null)
    }
    return (
      <div className="overlay" onClick={e => e.target === e.currentTarget && setModal(null)}>
        <div className="modal">
          <div className="mh"><h3>{task ? 'עריכת משימה' : 'משימה חדשה'}</h3><button className="mx" onClick={() => setModal(null)}>×</button></div>
          <form onSubmit={sub}><div className="mb"><div className="fg">
            <div className="frow full"><label>כותרת *</label><input required value={form.title} onChange={f('title')} placeholder="תיאור..."/></div>
            <div className="frow"><label>עדיפות</label><select value={form.priority} onChange={f('priority')}>{PRIORITIES.map(p => <option key={p.value} value={p.value}>{p.label}</option>)}</select></div>
            <div className="frow"><label>תאריך יעד</label><input type="date" value={form.dueDate} onChange={f('dueDate')}/></div>
            <div className="frow full"><label>איש קשר</label><select value={form.contactId} onChange={f('contactId')}><option value="">ללא</option>{contacts.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
          </div></div>
          <div className="mf">
            <button type="submit" className="btn btn-p">{task ? 'שמור' : 'הוסף'}</button>
            <button type="button" className="btn btn-o" onClick={() => setModal(null)}>ביטול</button>
            {task && <button type="button" className="del-link" onClick={() => { if (window.confirm('למחוק?')) { onDelete(task.id); setModal(null) } }}>מחק</button>}
          </div></form>
        </div>
      </div>
    )
  }

  const tabs = [
    { id: 'today',   l: '🔥 היום'    },
    { id: 'overdue', l: '⚠ באיחור'   },
    { id: 'open',    l: 'פתוחות'     },
    { id: 'snoozed', l: '😴 נדחו'    },
    { id: 'done',    l: '✅ הושלמו'  },
  ]

  const emptyMsg = {
    today:   '🎉 אין משימות להיום',
    overdue: '✅ אין משימות באיחור',
    open:    'אין משימות פתוחות',
    snoozed: 'אין משימות נדחות',
    done:    'אין משימות שהושלמו',
  }

  return (
    <>
      <div className="ph">
        <h2>משימות</h2>
        <button className="btn btn-p" onClick={() => setModal({ task: null })}><Ico.plus/>הוסף</button>
      </div>
      <div className="pb"><div className="card">
        <div className="filter-bar">
          {tabs.map(f => (
            <button key={f.id} className={`fp ${filter === f.id ? 'on' : ''}`}
              onClick={() => setFilter(f.id)}>
              {f.l}
              {cnts[f.id] > 0 && <span className="fp-cnt" style={{ background: f.id === 'overdue' ? '#fee2e2' : undefined, color: f.id === 'overdue' ? '#dc2626' : undefined }}>{cnts[f.id]}</span>}
            </button>
          ))}
        </div>

        {!filtered.length
          ? <div className="empty"><div className="empty-ico">✅</div><p>{emptyMsg[filter]}</p></div>
          : filtered.map(t => (
              <TaskRow
                key={t.id} t={t} contacts={contacts}
                onToggle={onToggle}
                onEdit={task => setModal({ task })}
                onDelete={onDelete}
                onSnooze={onSnooze}
              />
            ))
        }
      </div></div>
      {modal && <TaskModal task={modal.task}/>}
    </>
  )
}
